<?php /** @var MageMe\WebForms\Block\Form\Element\Script\Submit $block */ ?>
<?php
$_form = $block->getForm();
$_uid = $block->getUid();
?>
<script type="text/x-magento-init">
    {
        "#webform_<?= $_uid ?>": {
            "MageMe_WebForms/js/submit": {
                "url": "<?= $block->getUrl('webforms/form/submit',
                ['_secure' => true, 'ajax' => $block->isAjax()]); ?>",
                "uid": "<?= $block->getUid(); ?>",
                "isAjax": <?= var_export($block->isAjax()); ?>,
                "isDisplayedAfterSubmission": <?= var_export($_form->getIsDisplayedAfterSubmission()); ?>,
                "isScrolledAfterSubmission": <?= var_export($_form->getIsScrolledAfterSubmission()); ?>,
                "useCaptcha": <?= var_export($_form->useCaptcha()); ?>,
                "responseName": "<?= $_form->useCaptcha() ? $_form->getCaptcha()->getCaptcha()->getResponseName() : '' ?>",
                "messageSuccess": "<?= __('Success!')?>",
                "messageError": "<?= __('Error')?>",
                "messageCaptcha": "<?= __('Please click on the Captcha')?>",
                "messageRedirecting": "<?= __('Redirecting')?>",
                "messageComplete": "<?= __('Complete')?>",
                "messageUnknownError": "<?= __('Unknown error(s) occurred')?>"
            }
        }
    }
</script>
