<?php
/** @var MageMe\WebForms\Block\Form\Element\Script\Captcha $block */

use MageMe\WebForms\Helper\Captcha\Hcaptcha;

?>
<?php
/** @var Hcaptcha $hcaptcha */
$hcaptcha = $block->getCaptcha();
?>
<script type="text/x-magento-init">
{
    "#captcha-container-<?= /* @noEscape */ $block->getUid() ?>": {
        "Magento_Ui/js/core/app": {
            "components": {
                "<?= $block->getUid() ?>": {
                    "component": "webformsHCaptcha",
                    "publicKey": "<?= $hcaptcha->getPublicKey() ?>",
                    "size": "<?= $hcaptcha->getSize() ?>",
                    "theme": "<?= $hcaptcha->getTheme() ?>",
                    "languageCode": "<?= $block->getLocale() ?>",
                    "responseFieldName": "<?= $hcaptcha->getResponseName() ?>"
                }
            }
        }
    }
}
</script>