<?php
/** @var MageMe\WebForms\Block\Form\Element\Script\Captcha $block */

use MageMe\WebForms\Helper\Captcha\Recaptcha;

?>
<?php
/** @var Recaptcha $recaptcha */
$recaptcha = $block->getCaptcha();
?>
<script type="text/x-magento-init">
{
    "#captcha-container-<?= /* @noEscape */ $block->getUid() ?>": {
        "Magento_Ui/js/core/app": {
            "components": {
                "<?= $block->getUid() ?>": {
                    "component": "webformsReCaptcha",
                    "version": "<?= $recaptcha->getVersion() ?>",
                    "publicKey": "<?= $recaptcha->getPublicKey() ?>",
                    "position": "<?= $recaptcha->getPosition() ?>",
                    "theme": "<?= $recaptcha->getTheme() ?>",
                    "languageCode": "<?= $block->getLocale() ?>",
                    "responseFieldName": "<?= $recaptcha->getResponseName() ?>"
                }
            }
        }
    }
}
</script>