<?php
/** @var MageMe\WebForms\Block\Form\Element\Script\Captcha $block */

use MageMe\WebForms\Helper\Captcha\Turnstile;

?>
<?php
/** @var Turnstile $turnstile */
$turnstile = $block->getCaptcha();
?>
<script type="text/x-magento-init">
{
    "#captcha-container-<?= /* @noEscape */ $block->getUid() ?>": {
        "Magento_Ui/js/core/app": {
            "components": {
                "<?= $block->getUid() ?>": {
                    "component": "webformsTurnstile",
                    "publicKey": "<?= $turnstile->getPublicKey() ?>",
                    "size": "<?= $turnstile->getSize() ?>",
                    "theme": "<?= $turnstile->getTheme() ?>",
                    "languageCode": "<?= $block->getLocale() ?>",
                    "responseFieldName": "<?= $turnstile->getResponseName() ?>"
                }
            }
        }
    }
}
</script>