<?php
/** @var MageMe\WebForms\Block\Form\Element\Fieldset $block */

use MageMe\WebForms\Api\Data\FieldInterface;
use MageMe\WebForms\Api\Data\FieldsetInterface;
use MageMe\WebForms\Helper\LogicHelper;
use MageMe\WebForms\Model\Logic;

$_uid          = $block->getUid();
$fieldsetId    = $block->getFieldsetId();
$fieldset      = $block->getFieldset();
$isLabelHidden = $block->isLabelHidden();
?>
<fieldset id="fieldset_<?= $_uid . $fieldsetId ?>"
          class="fieldset fieldset-<?= $fieldsetId ?> <?php if (!empty($fieldset[FieldsetInterface::CSS_CLASS])) {
              echo $fieldset[FieldsetInterface::CSS_CLASS];
          } ?><?php if ($fieldset['logic_visibility'] == Logic::VISIBILITY_HIDDEN) {
              echo ' ' . LogicHelper::HIDDEN_CSS_CLASS;
          } ?>"
          style="<?php if (!empty($fieldset[FieldsetInterface::CSS_STYLE])) {
              echo $fieldset[FieldsetInterface::CSS_STYLE] . ";";
          } ?>"
          role="group"
          <?php if ($fieldsetId) { ?>aria-labelledby="legend_<?= $_uid . $fieldsetId ?>"<?php } ?>>

    <?php if (!empty($fieldset[FieldsetInterface::NAME]) && !$isLabelHidden) { ?>
        <h3 class="legend" id="legend_<?= $_uid . $fieldsetId ?>">
            <span><?= $block->applyTranslation($fieldset[FieldsetInterface::NAME]); ?></span>
        </h3>
    <?php } ?>

    <?php
    /** @var FieldInterface $field */
    foreach ($fieldset['fields'] as $field) {
        echo $block->getFieldBlock()->setField($field)->toHtml();
    } ?>
</fieldset>