<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ProductAttachment
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/**
 * Block
 *
 * @var $block \Bss\ProductAttachment\Block\Attachment\Ajax
 */
$attachments = $block->getAttachments();
$storeId = $block->getStoreId();
$helper = $block->getHepler();
$customerGroupId = $helper->getCustomerGroupId();

?>
<?php if (!empty($attachments)): ?>
    <ul class='attachments'>
        <?php foreach ($attachments as $key => $value): ?>
            <?php if ($block->unlimit($value['downloaded_time'], $value['limit_time'])
                && $block->inStoreView($value['store_id'], $storeId)
                && $block->inCustomerGroup($value['customer_group'], $customerGroupId)
                && $value['status']): ?>
                <?php if ($value['type'] != $block::LINK_ATTACHMENT): ?>
                    <li>
                        <a class='attachment_download'
                           id='<?php echo $value['file_id'] ?>'
                           title='<?php echo $value['uploaded_file'] ?>'
                           href='<?php echo $helper->getAtttachmentUrl().$value['uploaded_file'] ?>'
                           download='<?php echo $value['uploaded_file'] ?>'
                        >
                            <img src='<?php echo $block->getIconUrl($value['uploaded_file']) ?>' width='25px' height='25px'>
                            <?php echo $value['title'] ?>
                            <?php echo $helper->getAttachmentSizeFlag() ? " ({$value['size']}KB) " : ""; ?>
                            <?php echo $helper->getDownloadTimeFlag() ?
                                "<i><span class='attDownloadTime".$value['file_id']."'> ( " . $value['downloaded_time'] . " downloads )</span></i>" :
                                ""; ?>
                            <span id="attLimited<?php echo $value['file_id'] ?>"></span>
                        </a>
                    </li>
                <?php else: ?>
                    <li>
                        <a class='attachment_download'
                           href='<?php echo $value['uploaded_file'] ?>'
                           id='<?php echo $value['file_id'] ?>'
                           title='<?php echo $value['uploaded_file'] ?>'
                           target='_blank'>
                            <img src='<?php echo $block->getLinkIcon() ?>' width='25px' height='25px'>
                            <?php echo $value['title'] ?>
                            <?php echo $helper->getDownloadTimeFlag() ?
                                "<i><span class='attDownloadTime".$value['file_id']."'>( " . $value['downloaded_time'] . " downloads )</span></i>" :
                                ""; ?>
                            <span id="attLimited<?php echo $value['file_id'] ?>"></span>
                        </a>
                    </li>
                <?php endif ?>

            <?php endif ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>
