<!-- Add the necessary HTML structure and CSS classes -->

<?php

    $isShowResidentialOpt = $this->isShowResidentialOption();

?>

<?php if ($isShowResidentialOpt) { ?>
<div class="summary-cart-items" style="margin-bottom: 30px;">
    <p style="font-weight: 600;">The delivery address is a :</p>

    <input type="radio" name="custom_radio" value="1" />
    <label>Residential</label>

    <input type="radio" name="custom_radio" value="2" />
    <label>Business</label>
</div>
<?php } ?>