<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Reports Base for Magento 2
 */
/* @var Escaper $escaper */
/* @var Chart $block */

use Amasty\Reports\Block\Adminhtml\Report\Chart;
use Magento\Framework\Escaper;

$axis = $block->getAxisFields();
$collection = $block->getCollection();
$totalConversionRate = 0;
?>

<div class="amreports-amchart-wrapper" data-role="amreports-content">
    <?php if ($collection->getSize()): ?>

        <?php $params['interval'] = $escaper->escapeHtml($block->getInterval()); ?>
        <?php foreach ($collection as $item) {
            $chartData[] = [
                "date" => $escaper->escapeHtml($item->getData($axis['y'])),
                "conversion" => $escaper->escapeHtml($item->getData('conversion')) ?: 0,
            ];
            $totalConversionRate += $item->getData('conversion');
        } ?>

        <?php if ($totalConversionRate): ?>
            <div id="chart-customers" class="amreports-amchart-container" data-chart-identifier="conversion"></div>

            <script>
                require([
                    "Amasty_Reports/vendor/amcharts4/core.min"
                ], function () {
                    require([
                        "jquery",
                        "<?= /* @noEscape */ $block->getWidgetName('amreports_multi_linear_chart') ?>"
                    ], function ($, widget) {
                        widget({
                            "data" : <?= /* @noEscape */ json_encode($chartData); ?>,
                            "params" : <?= /* @noEscape */ json_encode($params); ?>,
                            "selectorInit" : "chart-customers"
                        }, $('#chart-customers'));
                    });
                });
            </script>
        <?php endif; ?>

        <div class="listing">
            <?= /* @noEscape */ $block->getChildHtml() ?>
        </div>
    <?php endif; ?>
</div>
