<?php
/**
 * @var Country $block
 */

use MageMe\WebForms\Block\Form\Element\Field\Type\Country;

$validationRules = $block->getValidationRules();
$validationDescriptions = $block->getValidationDescriptions();
$_countries = $block->getFieldOptions();
?>
<?php if (count($_countries) > 0): ?>
    <select id='<?= $block->getFieldId() ?>'
            name='<?= $block->getFieldName() ?>'
            class='<?= $block->getFieldClass() ?>'
            style='<?= $block->getFieldStyle() ?>'
            <?php if ($validationRules) { ?>
                data-validate="{<?= implode(", ", $validationRules); ?>}"
            <?php } ?>
            <?php foreach ($validationDescriptions as $key => $data) {
                echo $key . '=' . '"' . htmlspecialchars((string)$data) . '"';
            }
            ?>
            <?php if ($block->getIsLabelHidden()) { ?>aria-label="<?= $block->getFieldLabel() ?>"
            <?php } else { ?> aria-labelledby="label_<?= $block->getFieldId() ?>" <?php } ?>
            <?php if ($block->getIsRequired()) { ?>aria-required="true"<?php } ?>
            <?php if ($block->getAutocomplete()) { ?>autocomplete="<?= $block->getAutocomplete() ?>" <?php } ?>
            <?= htmlspecialchars((string)$block->getCustomAttributes()) ?>
    >
        <?php foreach ($_countries as $_country): ?>
            <?php $selected = ($block->getFieldValue() == $_country['value']) ? 'selected="selected"' : ''; ?>
            <option value="<?= $_country['value'] ?>" <?= $selected ?>>
                <?= $block->applyTranslation($_country['label']); ?>
            </option>
        <?php endforeach; ?>
    </select>
<?php endif; ?>
