<?php
/**
 * @var Password $block
 */

use MageMe\WebForms\Block\Form\Element\Field\Type\Password;

$validationRules        = $block->getValidationRules();
$validationDescriptions = $block->getValidationDescriptions();
?>
<div id='<?= $block->getFieldId() ?>container' class="password-container">
    <input id='<?= $block->getFieldId() ?>'
           name='<?= $block->getFieldName() ?>'
           type='password'
           class='<?= $block->getFieldClass() ?>'
           style='<?= $block->getFieldStyle() ?>'
           placeholder="<?= $block->getPlaceholder() ?>"
        <?= $block->getMinPasswordLength() ?>
        <?= $block->getComplexitySymbolsCount() ?>
           autocomplete="off"
        <?php if ($validationRules) { ?>
            data-validate="{<?= implode(", ", $validationRules); ?>}"
        <?php } ?>
        <?php foreach ($validationDescriptions as $key => $data) {
            echo $key . '=' . '"' . htmlspecialchars((string)$data) . '"';
        }
        ?>
           <?php if ($block->getIsLabelHidden()) { ?>aria-label="<?= $block->getFieldLabel() ?>"
           <?php } else { ?> aria-labelledby="label_<?= $block->getFieldId() ?>" <?php } ?>
           <?php if ($block->getIsRequired()) { ?>aria-required="true"<?php } ?>
           <?php if ($block->getAutocomplete()) { ?>autocomplete="<?= $block->getAutocomplete() ?>" <?php } ?>
           <?php if ($block->getMatchValueFieldId()) { ?>data-match-id="<?= $block->getMatchValueFieldId() ?>"<?php } ?>
        <?= htmlspecialchars((string)$block->getCustomAttributes()) ?>
    />
    <?php if ($block->getIsComplexityEnabled()) { ?>
        <div id="<?= $block->getFieldId() ?>password-strength-meter-container" data-role="password-strength-meter"
             aria-live="polite">
            <div id="<?= $block->getFieldId() ?>password-strength-meter" class="password-strength-meter">
                <?= __('Password Strength') ?>:
                <span id="<?= $block->getFieldId() ?>password-strength-meter-label"
                      data-role="password-strength-meter-label">
                                <?= __('No Password') ?>
                            </span>
            </div>
        </div>
    <?php } ?>
</div>

<?php if ($block->getIsComplexityEnabled()) { ?>
    <script type="text/x-magento-init">
    {
        "#<?= $block->getFieldId() ?>container": {
            "passwordStrengthIndicator": {
                "formSelector": "",
                "emailSelector": ""
            }
        }
    }

    </script>
<?php } ?>
