<?php
/**
 * @var Swatches $block
 */

use MageMe\WebForms\Block\Form\Element\Field\Type\Swatches;

$validationRules = $block->getValidationRules();
$validationDescriptions = $block->getValidationDescriptions();
?>

<div class="mm-swatches">
    <?php
    $options = $block->getFieldOptions();
    foreach ($block->getFieldOptions() as $i => $option) {
        $checked = false;
        if ($option["checked"]) {
            $checked = 'checked';
        }
        if (isset($option["value"]) && empty($option['optgroup']) && empty($option['optgroup_close'])) {
            $label = $block->applyTranslation($option["label"]);
            if ($option["image_src"]) {
                $label = "<figure><img src='{$option['image_src']}'/><figcaption>{$label}</figcaption></figure>";
            }
            ?>

            <div class='field choice option-<?= $i ?>'
                 style='<?= $block->getFieldStyle() ?>'
            >
                <label id="<?= $block->getFieldId() . $i ?>_label">
                    <input id='<?= $block->getFieldId() . $i ?>'
                           name='<?= $block->getFieldName() ?>'
                           type='<?= $block->getFieldInputType() ?>'
                           value="<?= htmlspecialchars((string)$option["value"]) ?>"
                           class='<?= $block->getFieldClass() ?>'
                        <?php if ($validationRules) { ?>
                            data-validate="{<?= implode(", ", $validationRules); ?>}"
                        <?php } ?>
                        <?php foreach ($validationDescriptions as $key => $data) {
                            echo $key . '=' . '"' . htmlspecialchars((string)$data) . '"';
                        }
                        ?>
                           data-uid="<?= $block->getFieldUid() ?>"
                           aria-labelledby="<?= $block->getFieldId() . $i ?>_label<?php if(!$block->getField()->getIsLabelHidden()){?> label_<?= $block->getFieldId() ?><?php } ?>"
                        <?= $checked ?>
                        <?= htmlspecialchars((string)$block->getCustomAttributes()) ?>
                    />
                    <span style='<?= $block->getSpanStyle($option); ?>'><?= $label ?></span>
                </label>
                <?php
                $tooltip = $block->getField()->getTooltip($option["value"]);
                if ($tooltip) {
                    echo $block->getTooltipBlock()->setTooltip($tooltip)->toHtml();
                }
                ?>

            </div>

            <?php
        }
    }
    ?>
</div>
