<?php

    $fusedship_product_data_arr = $block->getFusedshipProductData();

    $use_fusedship_rates = $fusedship_product_data_arr[0]['use_fusedship_rates'] ?? 0;

    $package_types = ['', 'Carton', 'Skid', 'Pallet', 'Pack', 'Crate', 'Roll', 'Satchel', 'Stillage', 'Tube', 'Bag'];

    $cartons = $block->getProductCartons() ?? [];

?>

<select style="display:none;" id="hidden-package-types">
<?php foreach($package_types as $package_type): ?>
    <option value="<?php echo $package_type; ?>"><?php echo $package_type; ?></option>
<?php endforeach; ?>
</select>
<fieldset class="admin__fieldset">
    <div class="admin__field">
        <label class="admin__field-label">Enable Fusedship Rates for this product?</label>
        <div class="admin__field-control">
            <input type="checkbox" id="useFusedshipRatesToggle" <?php if($use_fusedship_rates == '1'){ echo 'checked="checked"'; } ?> />

            <input type="hidden" name="use_fusedship_rates" value="<?php echo $use_fusedship_rates; ?>" data-form-part="product_form" />
        </div>
    </div>
</fieldset>


<fieldset class="admin__fieldset" id="box-count-container" style="display: <?php echo ($use_fusedship_rates == 1 ? 'block;' : 'none;'); ?>">
    <div class="admin__field">
        <label class="admin__field-label">No. of boxes:</label>
        <div class="admin__field-control">
            <?php
                $box_count = count($cartons) ? count($cartons) : 1;
            ?>
            <input type="number" min="1" value="<?php echo $box_count; ?>" id="box_count"/>
        </div>
    </div>
</fieldset>

<div id="fusedship-carton-container" style="display: <?php echo ($use_fusedship_rates == 1 ? 'block;' : 'none;'); ?>">

    <button class="action-basic" id="add-box">+ Add Box</button><br/><br/>
    <table class="data-grid data-grid-draggable" id="cartons">
        <thead>
            <tr>
                <th class="data-grid-th _sortable _draggable _ascend">Length(cm)</th>
                <th class="data-grid-th _sortable _draggable _ascend">Width(cm)</th>
                <th class="data-grid-th _sortable _draggable _ascend">Height(cm)</th>
                <th class="data-grid-th _sortable _draggable _ascend">Weight(kg)</th>
                <th class="data-grid-th _sortable _draggable _ascend">Package Type</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
    <tbody>
        <?php if(!empty($cartons)): ?>
            <?php foreach($cartons as $ck => $carton): ?>
                <tr>
                    <td>
                        <input type="number" class="carton-length" name="carton_length[<?php echo $ck ?>]" value="<?php echo $carton['carton_length']; ?>" data-form-part="product_form">
                    </td>
                    <td>
                        <input type="number" class="carton-width" name="carton_width[<?php echo $ck ?>]" value="<?php echo $carton['carton_width']; ?>"
                        data-form-part="product_form">
                    </td>
                    <td>
                        <input type="number" class="carton-height" name="carton_height[<?php echo $ck ?>]" value="<?php echo $carton['carton_height']; ?>" data-form-part="product_form">
                    </td>
                    <td>
                        <input type="number" class="carton-weight" name="carton_weight[<?php echo $ck ?>]" value="<?php echo $carton['carton_weight']; ?>" data-form-part="product_form">
                    </td>
                    <td>
                        <select class="admin__control-select carton-package-type" name="package_type[<?php echo $ck ?>]" data-form-part="product_form">
                            <?php foreach($package_types as $package_type): ?>
                                <option value="<?php echo $package_type; ?>" <?php if(isset($carton['package_type'] ) && $carton['package_type'] == $package_type) { echo"selected"; } ?>><?php echo $package_type; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td>
                        <button class="action-basic remove-box">Remove</button>
                    </td>
                </tr>
            <?php endforeach; ?>

        <?php else: ?>
            <tr>
                <td>
                    <input type="number" class="carton-length" name="carton_length[0]" value="" data-form-part="product_form">
                </td>
                <td>
                    <input type="number" class="carton-width" name="carton_width[0]" value="" data-form-part="product_form">
                </td>
                <td>
                    <input type="number" class="carton-height" name="carton_height[0]" value="" data-form-part="product_form">
                </td>
                <td>
                    <input type="number" class="carton-weight" name="carton_weight[0]" value="" data-form-part="product_form">
                </td>
                <td>
                    <select class="admin__control-select carton-package-type" name="package_type[0]" data-form-part="product_form">
                        <?php foreach($package_types as $package_type): ?>
                            <option value="<?php echo $package_type; ?>"><?php echo $package_type; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td>
                    <button class="action-basic remove-box">Remove</button>
                </td>
            </tr>
        <?php endif; ?>

    </tbody>
    </table>
</div>

<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){
        $( document ).ready(function() {
            $(document).on( 'change', '#useFusedshipRatesToggle', function() {

                if($(this).is(':checked')){
                    $('input[name=use_fusedship_rates').val(1);
                    $('#fusedship-carton-container').show();
                    $('#box-count-container').show();
                } else {
                    $('input[name=use_fusedship_rates').val(0);
                    $('#fusedship-carton-container').hide();
                    $('#box-count-container').hide();
                }
            });

            $(document).on('click', '#add-box', function () {
                var box_count = parseInt($('#box_count').val());

                $('#box_count').val(box_count + 1).trigger('change');
            });

            $(document).on('click', '.remove-box', function () {
                var box_count = parseInt($('#box_count').val());

                if((box_count - 1) <= 0) return false;

                $(this).closest('tr').remove();


                $('#box_count').val(box_count - 1).trigger('change');
            });

            function generateBox(boxes) {

                var trow = '';
                var options = $('#hidden-package-types').html();


                for(var i=0 ; i < boxes.length; i++) {
                    var thisBox = boxes[i];

                    trow += '<tr>';

                    trow += '<td> <input type="number" class="carton-length"  name="carton_length['+ i +']" value="'+ thisBox.carton_length +'" data-form-part="product_form"></td>';

                    trow += '<td> <input type="number" class="carton-width" name="carton_width['+ i +']" value="'+ thisBox.carton_width +'" data-form-part="product_form"></td>';

                    trow += '<td> <input type="number" class="carton-height" name="carton_height['+ i +']" value="'+ thisBox.carton_height +'" data-form-part="product_form"></td>';

                    trow += '<td> <input type="number" class="carton-weight" name="carton_weight['+ i +']" value="'+ thisBox.carton_weight+'" data-form-part="product_form"></td>';

                    trow += '<td> <select class="admin__control-select carton-package-type" name="package_type['+ i +']" data-form-part="product_form">'+ options +'</select></td>';

                    trow += '<td><button class="action-basic remove-box">Remove</button></td>';

                    trow += '</tr>';
                }


                $('#cartons tbody').html(trow);


                var idx = 0;
                $(".carton-package-type").each(function() {
                    $(this).val(boxes[idx].carton_package_type);
                    idx++;
                });



            }

            $(document).on('change', '#box_count', function () {
                var box_count = $(this).val();

                if(!box_count) box_count = 1;

                var current_boxes = [];

                $("#cartons tbody tr").each(function() {
                    var length = $(this).find(".carton-length").val();
                    var width = $(this).find(".carton-width").val();
                    var height = $(this).find(".carton-height").val();
                    var weight = $(this).find(".carton-weight").val();
                    var package_type = $(this).find(".carton-package-type").val();

                    current_boxes.push({
                        carton_length: length,
                        carton_width: width,
                        carton_height: height,
                        carton_weight: weight,
                        carton_package_type: package_type
                    });

                });


                var boxes = [];

                if(current_boxes.length >= box_count) {
                    boxes = current_boxes.slice(0,box_count);
                } else {
                    boxes = current_boxes;

                    var last_box_data = boxes[boxes.length - 1];

                    while(boxes.length < box_count) {
                        boxes.push({
                            carton_length: last_box_data.carton_length,
                            carton_width: last_box_data.carton_width,
                            carton_height: last_box_data.carton_height,
                            carton_weight: last_box_data.carton_weight,
                            carton_package_type: last_box_data.carton_package_type
                        });
                    }
                }

                console.log(boxes);


                generateBox(boxes);

            });

        });
    });
</script>
