<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ProductAttachment
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/**
 * Block
 *
 * @var $block \Bss\ProductAttachment\Block\Footer\View 
 */

$helper = $block->getHepler();
$customerGroupId = $helper->getCustomerGroupId();
$storeId = $block->getStoreId();
$postUrl = $block->getBaseUrl().'productattachment/render/footerattachment';
$updateTimeUrl = $block->getBaseUrl().'productattachment/update/downloadtime';

?>
<span class="bss productattachment">
    <input type="hidden" id="att_footer_customer_id" value="<?php echo $customerGroupId ?>">
    <input type="hidden" id="att_footer_store_id" value="<?php echo $storeId ?>">
    <span class="productattachment_footer">
    </span>
</span>

<script type="text/x-magento-init">
	{
	"*": 
        {
            "Bss_ProductAttachment/js/renderfooter": {
                "postUrl": "<?php echo $postUrl ?>"
            },
            "Bss_ProductAttachment/js/downloadtimefooter": {
                "postUrl": "<?php echo $updateTimeUrl ?>"
            }
        }
	}
</script>
