<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ProductAttachment
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/**
 * Block
 *
 * @var $block \Bss\ProductAttachment\Block\Product\View 
 */

$helper = $block->getAttachmentHelper();
$product = $block->getProduct();
$productId = $product->getId();

$customerGroupId = $helper->getCustomerGroupId();
$storeId = $block->getStoreId();
$postUrl = $block->getBaseUrl().'productattachment/render/attachmentlist';
?>
<?php if ($helper->getShowInProductTabFlag() && $helper->hasAttachment($productId)): ?>
    <div class="bss tab productattachment">
        <input type="hidden" id="attachment_tab_productId" value="<?php echo $productId ?>">
        <input type="hidden" id="attachment_tab_customerId" value="<?php echo $customerGroupId ?>">
        <input type="hidden" id="attachment_tab_storeId" value="<?php echo $storeId ?>">
        <div class="productattachment_listattachment_tab">
        </div>
    </div>
    <script type="text/x-magento-init">
    {
    "*": 
        {
            "Bss_ProductAttachment/js/renderproducttab": {
                "postUrl": "<?php echo $postUrl ?>"
            }
        }
    }
    </script>
<?php endif ?>
