<div class="content-header ad-header">
    <h3 class="icon-head head-sales-order-invoice ad-title"><?php echo $this->getHeaderText() ?></h3>
    <p class="form-buttons ad-form-buttons">
        <button  onclick="setLocation('<?php echo $this->getBackUrl() ?>')" class="scalable back" type="button"
                 title="Back">
            <span><span><span>Back</span></span></span>
        </button>
        <button  onclick="setLocation(window.location.href)" class="scalable " type="button" title="Reset">
            <span><span><span>Reset</span></span></span>
        </button>
    </p>
</div>

<?php $objectManager = $this->getobjectManager(); ?>
<?php

$articletypes = $objectManager->create('Biztech\Ausposteparcel\Model\Cresource\Articletype\Collection');
$articletypes->load();
$orderId = $this->getOrder();
$_order = $objectManager->create('\Magento\Sales\Model\Order')->load($orderId);
$consignment = $this->getConsignment($orderId);
$use_order_total_weight = $this->getStoreConfig('carriers/ausposteParcel/useTotalOrderWeight');
$use_article_dimensions = $this->getStoreConfig('carriers/ausposteParcel/useArticleDimensions');
$weight = $objectManager->create('Biztech\Ausposteparcel\Helper\Info')->getOrderWeight($_order);
$weightPerArticle = $objectManager->create('Biztech\Ausposteparcel\Helper\Info')->getAllowedWeightPerArticle();
if ($use_order_total_weight == 1) {
    if ($weight == 0) {
        $default_article_weight = $this->getStoreConfig('carriers/ausposteParcel/defaultWeight');
        if ($default_article_weight) {
            $weight = $default_article_weight;

        }
    
    }

}

$selected = false;
$selectedWeight = 0;
if ($weight <= $weightPerArticle) {
    $upCheck = $weightPerArticle - $weight;
    if ($objectManager->create('Biztech\Ausposteparcel\Helper\Info')->articletypeMatch($articletypes, $weight)) {
        $selectedWeight = $weight;
    
    } else {
        for ($i = .01; $i <= $upCheck; $i = $i + 0.01) {
            $newUpWeight = $weight + $i;
            if ($objectManager->create('Biztech\Ausposteparcel\Helper\Info')->articletypeMatch($articletypes, $newUpWeight)) {
                $selectedWeight = '' . $newUpWeight . '';
                break;
            
            }
        
        }
    
    }

}
?>

<form name="edit_form" id="edit_form" method="post" action="<?php echo $this->getSaveUrl() ?>">
    <?php echo $this->getBlockHtml('formkey') ?>
    <input id="order_id" type="hidden" name="order_id" value="<?php echo $this->getOrder(); ?>"/>
    <input id="number_of_articles" name="number_of_articles" size="4" value="1" type="hidden"/>
    <input id="source" type="hidden" name="source" value="grid"/>

    <?php if ($use_article_dimensions == 1):
        ?>
        <div class="box" id="articletypes">
            Article Type&nbsp;&nbsp;
            <select id="articles_type" name="articles_type" class="required-entry2" >
                <?php
                foreach ($articletypes->getData() as $articletype) {
                    ?>
                    <option
                        value="<?php echo $articletype->getName() . '<=>' . $articletype->getWeight() . '<=>' . $articletype->getHeight() . '<=>' . $articletype->getWidth() . '<=>' . $articletype->getLength() ?>"
                        <?php
                        if ($articletype->getWeight() == $selectedWeight && !$selected) {
                            echo 'selected="selected"';
                            $selected = true;
                        
                        }
                        ?>
                        >
                            <?php echo $articletype->getName() . ' (' . $articletype->getWeight() . 'kg - ' . $articletype->getHeight() . 'x' . $articletype->getWidth() . 'x' . $articletype->getLength() . ')' ?>
                    </option>
                    <?php
                
                }
                ?>
                <option value="Custom" <?php echo ($weight > $weightPerArticle) ? 'selected="selected"' : '' ?>>Custom
                </option>
            </select>
            &nbsp;&nbsp;&nbsp;&nbsp;

            <button  onclick="return submitForm2()"
                     class="create-consignment1 scalable save submit-button <?php
                        if ($this->getOrder()->getStatus() == 'complete') {
                            echo 'disabled';
                        
                        }
                        ?>" type="button" title="Submit" <?php
if ($this->getOrder()->getStatus() == 'complete') {
    echo 'disabled="disabled"';

}
?>><span><span><span>Add Article</span></span></span></button>

        </div>
        <?php
    else:
        ?>
        <input type="hidden" id="articles_type" name="articles_type" value="Custom"/>
        <?php
    endif; ?>

    <div class="box custom_articles_template" style="display:none">
        <h3>Article</h3>
        <span class="field-row1">
            <label class="normal" for="article_description">
                <?php echo (__('Description:')); ?><span class="required">*</span>
            </label>
            <input id="article_description" name="article[description]" class="required-entry input-text admin__control-text" value="Article"/>
        </span>
        <span class="field-row1">
            <label class="normal" for="article_weight">
                <?php echo (__('Weight (Kgs):')); ?><span class="required">*</span>
            </label>
            <?php if ($use_order_total_weight == 1):
                ?>
                <input size="10" id="article_weight" class="required-entry input-text admin__control-text" name="article[weight]"
                       class="required-entry positive-number maximum-value" label="Weight"
                       value="<?php echo ($weight > $weightPerArticle) ? $weightPerArticle : $weight ?>"/>
                    <?php
            else:
                ?>
                <input size="10" id="article_weight" class="required-entry input-text admin__control-text" name="article[weight]"
                       class="required-entry positive-number" label="Weight"
                       value="<?php echo $this->getStoreConfig('carriers/ausposteParcel/defaultWeight') ?>"/>
                    <?php
            endif; ?>
        </span>
        <span class="field-row1">
            <label class="normal" for="article_height">
                <?php echo (__('Height (cm):')); ?>
            </label>
            <input size="10" id="article_height" class="positive-number input-text admin__control-text" label="Height"
                   name="article[height]"
                   value="<?php echo $this->getStoreConfig('carriers/ausposteParcel/defaultHeight') ?>"/>
        </span>
        <span class="field-row1">
            <label class="normal" for="article_width">
                <?php echo (__('Width (cm):')); ?>
            </label>
            <input size="10"  id="article_width" class="positive-number input-text admin__control-text" label="Width"
                   name="article[width]"
                   value="<?php echo $this->getStoreConfig('carriers/ausposteParcel/defaultWidth') ?>"/>
        </span>
        <span class="field-row1">
            <label class="normal" for="article_length">
                <?php echo (__('Length (cm):')); ?>
            </label>
            <input size="10"  id="article_length" class="positive-number input-text admin__control-text" label="Length"
                   name="article[length]"
                   value="<?php echo $this->getStoreConfig('carriers/ausposteParcel/defaultLength') ?>"/>
        </span>
        <span class="field-row1">
            <label class="normal" for="unit_value">
                <?php echo (__('Unit Value:')); ?>
            </label>
            <input size="10"  id="article_unit_value" class="positive-number input-text admin__control-text" label="Unit Value"
                   name="article[unit_value]"
                   value="1"/>
        </span>
    </div>

    <div id="custom_articles" style="display:none">
        <div id="custom_articles_container">
        </div>

        <button  onclick="backToArticletype()" class="scalable back backToArticletype" type="button"
                 title="Back">
            <span><span><span>Back to Article Type</span></span></span>
        </button>
        &nbsp;&nbsp;
        <button  onclick="return submitForm()"
                 class="scalable save submit-button <?php
                    if ($_order->getStatus() == 'complete') {
                        echo 'disabled';
                    
                    }
                    ?>" type="button" title="Submit" <?php
if ($_order->getStatus() == 'complete') {
    echo 'disabled="disabled"';

}
?>><span><span><span>Add Article</span></span></span></button>
    </div>

    <div>
        <br/>
        <a href="javascript:void(0)" class="edit-consignments-defaults" ><span>Show Default Consignment Settings</span></a>
        <br/>
        <br/>
    </div>

    <div class="box consignment-fields" style="display:none">
        <h3>Consignment Fields</h3>
        <table width="100%" border="0" cellspacing="6" cellpadding="6" class="tablecustom ad-table">
            <tr>
                <td width="20%"><?php echo (__('Allow Partial Delivery')); ?></td>
                <td>
                    <?php if ($objectManager->create('Biztech\Ausposteparcel\Helper\Info')->isDisablePartialDeliveryMethod($_order->getId())):
                        ?>
                        <select id="partial_delivery_allowed"  class="select admin__control-select" style="width : 100%" name="partial_delivery_allowed" disabled="disabled">
                            <option value="0">No</option>
                        </select>
                        <?php
                    else:
                        ?>
                        <select id="partial_delivery_allowed" class="select admin__control-select" style="width : 100%" name="partial_delivery_allowed">
                            <option
                                value="1" <?php echo(($consignment['partial_delivery_allowed']) == 1 ? 'selected' : '') ?>>
                                Yes
                            </option>
                            <option
                                value="0" <?php echo(($consignment['partial_delivery_allowed']) != 1 ? 'selected' : '') ?>>
                                No
                            </option>
                        </select>
                        <?php
                    endif; ?>
                </td>
            </tr>

            <?php if ($objectManager->create('Biztech\Ausposteparcel\Helper\Info')->isCashToCollect($_order->getId())):
                ?>
                <tr>
                    <td><?php echo (__('Cash to collect')); ?></td>
                    <td><input id="cash_to_collect" name="cash_to_collect"
                               value="<?php echo $consignment['cash_to_collect'] ?>"/></td>
                </tr>
                <?php
            endif; ?>

            <tr>
                <td><?php echo (__('Enable Delivery Signature')); ?></td>
                <td><select  class="select admin__control-select" style="width : 100%" id="delivery_signature_allowed" name="delivery_signature_allowed">
                        <option
                            value="1" <?php echo($consignment['delivery_signature_allowed'] == 1 ? 'selected' : '') ?>>
                            Yes
                        </option>
                        <option
                            value="0" <?php echo($consignment['delivery_signature_allowed'] != 1 ? 'selected' : '') ?>>
                            No
                        </option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Enable Transit Cover Amount')); ?></td>
                <td><select class="select admin__control-select" style="width : 100%" id="transit_cover_required" name="transit_cover_required">
                        <option
                            value="1" <?php echo($this->getStoreConfig('carriers/ausposteParcel/insurance') == 1 ? 'selected' : '') ?>>
                            Yes
                        </option>
                        <option
                            value="0" <?php echo($this->getStoreConfig('carriers/ausposteParcel/insurance') != 1 ? 'selected' : '') ?>>
                            No
                        </option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Transit Cover Amount')); ?></td>
                <td><input id="transit_cover_amount" class="positive-number input-text admin__control-text" style="width: 100%" label="Transit Cover Amount"
                           name="transit_cover_amount"
                           value="<?php echo $this->getStoreConfig('carriers/ausposteParcel/defaultInsuranceValue') ?>"/>
                </td>
            </tr>
            <tr>
                <td><?php echo (__('Is Shipment Contains Dangerous Goods ?')); ?></td>
                <td><select class="select admin__control-select" style="width : 100%" id="contains_dangerous_goods" name="contains_dangerous_goods">
                        <option
                            value="1" <?php echo($consignment['contains_dangerous_goods'] == 1 ? 'selected' : '') ?>>Yes
                        </option>
                        <option
                            value="0" <?php echo($consignment['contains_dangerous_goods'] != 1 ? 'selected' : '') ?>>No
                        </option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Create Labels')); ?></td>
                <td><select class="select admin__control-select" style="width : 100%" id="print_return_labels" name="print_labels">
                        <option value="1" <?php echo($consignment['is_label_created'] == 1 ? 'selected' : '') ?>>Yes
                        </option>
                        <option value="0" <?php echo($consignment['is_label_created'] != 1 ? 'selected' : '') ?>>No
                        </option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Print Return Labels')); ?></td>
                <td><select class="select admin__control-select" style="width : 100%" id="print_return_labels" name="print_return_labels">
                        <option value="1" <?php echo($consignment['print_return_labels'] == 1 ? 'selected' : '') ?>>
                            Yes
                        </option>
                        <option value="0" <?php echo($consignment['print_return_labels'] != 1 ? 'selected' : '') ?>>No
                        </option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Australia Post Email Notification')); ?></td>
                <td><select class="select admin__control-select" style="width : 100%" id="email_notification" name="email_notification">
                        <option value="1" <?php echo($consignment['email_notification'] == 1 ? 'selected' : '') ?>>Yes
                        </option>
                        <option value="0" <?php echo($consignment['email_notification'] != 1 ? 'selected' : '') ?>>No
                        </option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Notify Customers on dispatch of Manifest')); ?></td>
                <td><select class="select admin__control-select" style="width : 100%" id="notify_customers" name="notify_customers">
                        <option value="1" <?php echo($consignment['notify_customers'] == 1 ? 'selected' : '') ?>>Yes
                        </option>
                        <option value="0" <?php echo($consignment['notify_customers'] != 1 ? 'selected' : '') ?>>No
                        </option>
                    </select></td>
            </tr>
        </table>

    </div>
    <div class="clear"></div>

    <!--<button  onclick="return submitForm()" class="scalable save submit-button" type="button" title="Submit"><span><span><span>Add Article</span></span></span></button>-->

</form>
<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui',
        'Magento_Ui/js/modal/modal',
        'prototype'

    ], function ($) {
        $jEparcel = jQuery.noConflict();
        $jEparcel(document).ready(function () {
            $jEparcel('.edit-consignments-defaults').click(function () {
                $jEparcel('.consignment-fields').slideToggle();
                if($jEparcel('.edit-consignments-defaults').html() == "<span>Show Default Consignment Settings</span>"){
                    $jEparcel('.edit-consignments-defaults').html("<span>Hide Default Consignment Settings</span>");
                }else{
                    $jEparcel('.edit-consignments-defaults').html("<span>Show Default Consignment Settings</span>");
                }
            });

            $jEparcel('#number_of_articles').blur(function () {
                var value = $jEparcel.trim($jEparcel(this).val());
                if (value.length == 0) {
                    alert('Articles should not be empty');
                    $jEparcel(this).val(1);
                }
                if (isNaN(value)) {
                    alert('Articles should be a number');
                    $jEparcel(this).val(1);
                }

                value = parseInt(value);
                if (value < 0) {
                    alert('Articles should be a postive number');
                    $jEparcel(this).val(1);
                }
            });

            if ($jEparcel('#articles_type').val() == 'Custom') {
                $jEparcel('.create-consignment1').hide();
                $jEparcel('.backToArticletype').hide();
                $jEparcel('#custom_articles').show();

                var number_of_articles = $jEparcel('#number_of_articles').val();
                for (var i = 1; i <= number_of_articles; i++) {
                    var box = $jEparcel('.custom_articles_template').clone();
                    box.removeClass('custom_articles_template');
                    box.find('h3').html(box.find('h3').html() + ' ' + i);
                    box.find('#article_description').val(box.find('#article_description').val() + ' ' + i);
                    box.show();
                    $jEparcel('#custom_articles_container').append(box);
                }
            }

            $jEparcel('#articles_type').change(function () {
                $jEparcel('.backToArticletype').hide();
                if ($jEparcel(this).val() == 'Custom') {
                    $jEparcel('.create-consignment1').hide();
                    $jEparcel('#articletypes').show();
                    $jEparcel('#custom_articles').show();

                    var number_of_articles = $jEparcel('#number_of_articles').val();
                    for (var i = 1; i <= number_of_articles; i++) {
                        var box = $jEparcel('.custom_articles_template').clone();
                        box.removeClass('custom_articles_template');
                        box.find('h3').html(box.find('h3').html() + ' ' + i);
                        box.find('#article_description').val(box.find('#article_description').val() + ' ' + i);
                        box.show();
                        $jEparcel('#custom_articles_container').append(box);
                    }
                } else {
                    $jEparcel('#articletypes').show();
                    $jEparcel('#custom_articles').hide();
                    $jEparcel('#custom_articles_container').html('');
                    $jEparcel('.create-consignment1').show();
                }
            });
        });
    });
</script>
<script>
<?php if ($use_order_total_weight == 1):
    ?>
        var weightPerArticle = '<?php echo $weightPerArticle ?>';
    <?php
endif; ?>


    function backToArticletype() {
        $jEparcel('#articletypes').show();
        $jEparcel('#custom_articles').hide();
        $jEparcel('#custom_articles_container').html('');
        $jEparcel('#articles_type').val($jEparcel('#articles_type > option:first').attr('value'));
    }

    function submitForm() {
        var valid = true;

        var value = $jEparcel.trim($jEparcel('#articles_type').val());
        if (value.length == 0 && valid) {
            valid = false;
            alert('Please select article type');
            return false;
        }

        $jEparcel('#custom_articles_container .required-entry').each(function () {
            var value = $jEparcel.trim($jEparcel(this).val());
            if (value.length == 0 && valid) {
                valid = false;
            }
        });
        if (!valid) {
            alert('Please enter all the mandatory fields');
            return false;
        }
        $jEparcel('.positive-number').each(function () {
            var value = $jEparcel.trim($jEparcel(this).val());
            var label = $jEparcel(this).attr('label');
            if (isNaN(value)) {
                alert(label + ' should be a number');
                valid = false;
            }

            value = parseInt(value);
            if (value < 0) {
                alert(label + ' should be a postive number');
                valid = false;
            }

        });
        if (!valid) {
            return false;
        }
<?php if ($use_order_total_weight == 1):
    ?>
            $jEparcel('.maximum-value').each(function () {
                var value = $jEparcel.trim($jEparcel(this).val());
                var label = $jEparcel(this).attr('label');
                value = parseFloat(value);
                if (value > weightPerArticle) {
                    alert('Allowed weight per article is ' + weightPerArticle);
                    valid = false;
                }

            });
            if (!valid) {
                return false;
            } else {
                $('edit_form').submit();
            }
    <?php
else:
    ?>
            $('edit_form').submit();
    <?php
endif; ?>
    }
    function submitForm2() {
        $('edit_form').submit();
    }
</script>
