<div class="content-header ad-header">
    <h3 class="icon-head head-sales-order-invoice ad-title"><?php //echo //$this->getHeaderText()   ?></h3>    
    <p class="form-buttons ad-form-buttons">
        <button onclick="setLocation('<?php echo $this->getBackUrl() ?>')" class="scalable back" type="button" title="Back">
            <span><span><span>Back</span></span></span>
        </button>
        <button onclick="setLocation(window.location.href)" class="scalable " type="button" title="Reset">
            <span><span><span>Reset</span></span></span>
        </button>
    </p>
</div>
<?php $objectManager = $this->getobjectManager(); ?>
<?php $_order = $objectManager->create('Magento\Sales\Model\Order')->load($this->getOrder()); ?>
<?php $consignment = $this->getConsignment($_order->getId(), $this->getRequest()->getParam('consignment_number')); ?>
<?php $articles = $this->getArticles(); ?>
<?php
$use_order_total_weight = (int) $this->getStoreConfig('carriers/ausposteParcel/useTotalOrderWeight');
$use_article_dimensions = (int) $this->getStoreConfig('carriers/ausposteParcel/useArticleDimensions');
if ($use_order_total_weight == 1) {
    $weight = $objectManager->create('Biztech\Ausposteparcel\Helper\Info')->getOrderWeight($_order);
    if ($weight == 0) {
        $default_article_weight = $this->getStoreConfig('carriers/ausposteParcel/defaultWeight');
        if ($default_article_weight) {
            $weight = $default_article_weight;
        }
    }
    $weightPerArticle = $objectManager->create('Biztech\Ausposteparcel\Helper\Info')->getAllowedWeightPerArticle();
}
?>
<form name="edit_form" id="edit_form" method="post" action="<?php echo $this->getSaveUrl() ?>">
    <?php echo $this->getBlockHtml('formkey') ?>
    <input id="order_id" type="hidden" name="order_id" value="<?php echo $this->getOrder(); ?>" />
    <input id="consignment_id" type="hidden" name="consignment_id" value="<?php echo $consignment['consignment_id'] ?>" />
    <input id="number_of_articles2" type="hidden" name="number_of_articles" value="<?php echo count($articles) ?>" />
    <input id="articles_type" type="hidden" name="articles_type" value="Custom" />
    <input id="source" type="hidden" name="source" value="grid" />

    <?php if (($use_order_total_weight == 1) && ($weight > $weightPerArticle)): ?>
        <h3>Total Order Weight: <strong><?php echo $weight ?></strong></h3>
    <?php endif; ?>

    <?php $i = 0; ?>
    <?php foreach ($articles as $article): ?>
        <div class="box">
            <h3>Article <?php echo $i + 1 ?></h3>
            <span class="field-row1">
                <label class="normal" for="article_description">
                    <?php echo (__('Description:')) ?><span class="required">*</span>
                </label>
                <input id="article_description<?php echo $i + 1 ?>" name="article<?php echo $i + 1 ?>[description]" class="required-entry" value="<?php echo $article['article_description'] ?>"/>
            </span>
            <span class="field-row1">
                <label class="normal" for="article_weight">
                    <?php echo (__('Weight (Kgs):')) ?><span class="required">*</span>
                </label>
                <input size="10"  id="article_weight<?php echo $i + 1 ?>" name="article<?php echo $i + 1 ?>[weight]" class="required-entry positive-number article_weight maximum-value" label="Weight" value="<?php echo $article['actual_weight'] ?>"/>
            </span>
            <?php //if ($use_article_dimensions == 1): ?>
            <span class="field-row1">
                <label class="normal" for="article_height">
                    <?php echo (__('Height (cm):')) ?>
                </label>
                <input size="10"  class="positive-number" label="Height" id="article_height<?php echo $i + 1 ?>" name="article<?php echo $i + 1 ?>[height]" value="<?php echo $article['height'] ?>"/>
            </span>
            <span class="field-row1">
                <label class="normal" for="article_width">
                    <?php echo (__('Width (cm):')) ?>
                </label>
                <input size="10"  class="positive-number" label="Width" id="article_width<?php echo $i + 1 ?>" name="article<?php echo $i + 1 ?>[width]" value="<?php echo $article['width'] ?>"/>
            </span>
            <span class="field-row1">
                <label class="normal" for="article_length">
                    <?php echo (__('Length (cm):')) ?>
                </label>

                <input size="10"  class="positive-number" label="Length" id="article_length<?php echo $i + 1 ?>" name="article<?php echo $i + 1 ?>[length]" value="<?php echo $article['length'] ?>"/>

                <input type="hidden" id="article_number<?php echo $i + 1 ?>" name="article<?php echo $i + 1 ?>[article_number]" value="<?php echo $article['article_number'] ?>"/>
            </span>
            <span class="field-row1">
                <label class="normal" for="article_unit_value">
                    <?php echo (__('Unit Value:')); ?>
                </label>

                <input size="10"  class="positive-number" label="Unit Value" id="article_unit_value<?php echo $i + 1 ?>" name="article<?php echo $i + 1 ?>[unit_value]" value="<?php echo $article['unit_value'] ?>"/>

                <input type="hidden" id="article_number<?php echo $i + 1 ?>" name="article<?php echo $i + 1 ?>[article_number]" value="<?php echo $article['article_number'] ?>"/>
            </span>
        </div>
        <?php $i++; ?>
    <?php endforeach; ?>
    <div class="box">
        <h3>Consignment Fields</h3>
        <table width="100%" border="0" cellspacing="6" cellpadding="6" class="tablecustom ad-table">
            <tr>
                <td width="20%"><?php echo (__('Allow Partial Delivery')) ?></td>
                <td>
                    <?php if ($objectManager->create('Biztech\Ausposteparcel\Helper\Info')->isDisablePartialDeliveryMethod($_order->getId())): ?>
                        <select id="partial_delivery_allowed" name="partial_delivery_allowed" disabled="disabled">
                            <option value="0">No</option>
                        </select>
                    <?php else: ?>
                        <select id="partial_delivery_allowed" name="partial_delivery_allowed" >
                            <option value="1" <?php echo (($consignment['partial_delivery_allowed']) == 1 ? 'selected' : '') ?>>Yes</option>
                            <option value="0" <?php echo (($consignment['partial_delivery_allowed']) != 1 ? 'selected' : '') ?>>No</option>
                        </select>
                    <?php endif; ?>
                </td>
            </tr>

            <?php if ($objectManager->create('Biztech\Ausposteparcel\Helper\Info')->isCashToCollect($_order->getId())): ?>
                <tr>
                    <td><?php echo (__('Cash to collect')) ?></td>
                    <td><input id="cash_to_collect" name="cash_to_collect"  value="<?php echo $consignment['cash_to_collect'] ?>"/></td>
                </tr>
            <?php endif; ?>

            <tr>
                <td><?php echo (__('Enable Delivery Signature')) ?></td>
                <td><select id="delivery_signature_allowed" name="delivery_signature_allowed" >
                        <option value="1" <?php echo ($consignment['delivery_signature_allowed'] == 1 ? 'selected' : '') ?>>Yes</option>
                        <option value="0" <?php echo ($consignment['delivery_signature_allowed'] != 1 ? 'selected' : '') ?>>No</option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Enable Transit Cover Amount')) ?></td>
                <td><select id="transit_cover_required" name="transit_cover_required">
                        <option value="1" <?php //echo ($article['is_transit_cover_required'] == 'Y' ? 'selected' : '')  ?>>Yes</option>
                        <option value="0" <?php //echo ($article['is_transit_cover_required'] != 'Y' ? 'selected' : '')  ?>>No</option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Transit Cover Amount')) ?></td>
                <td>
                    <input id="transit_cover_amount" class="positive-number" label="Transit Cover Amount" name="transit_cover_amount" value="<?php //echo $article['transit_cover_amount']  ?>" />
                </td>
            </tr>
            <tr>
                <td><?php echo (__('Is Shipment Contains Dangerous Goods ?')) ?></td>
                <td><select id="contains_dangerous_goods" name="contains_dangerous_goods">
                        <option value="1" <?php echo ($consignment['contains_dangerous_goods'] == 1 ? 'selected' : '') ?>>Yes</option>
                        <option value="0" <?php echo ($consignment['contains_dangerous_goods'] != 1 ? 'selected' : '') ?>>No</option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Create Labels')) ?></td>
                <td><select id="print_return_labels" name="print_labels">
                        <option value="1" <?php echo ($consignment['is_label_created'] == 1 ? 'selected' : '') ?>>Yes</option>
                        <option value="0" <?php echo ($consignment['is_label_created'] != 1 ? 'selected' : '') ?>>No</option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Print Return Labels')) ?></td>
                <td><select id="print_return_labels" name="print_return_labels">
                        <option value="1" <?php echo ($consignment['print_return_labels'] == 1 ? 'selected' : '') ?>>Yes</option>
                        <option value="0" <?php echo ($consignment['print_return_labels'] != 1 ? 'selected' : '') ?>>No</option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Australia Post Email Notification')) ?></td>
                <td><select id="email_notification" name="email_notification">
                        <option value="1" <?php echo ($consignment['email_notification'] == 1 ? 'selected' : '') ?>>Yes</option>
                        <option value="0" <?php echo ($consignment['email_notification'] != 1 ? 'selected' : '') ?>>No</option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Notify Customers on dispatch of Manifest')) ?></td>
                <td><select id="notify_customers" name="notify_customers">
                        <option value="1" <?php echo ($consignment['notify_customers'] == 1 ? 'selected' : '') ?>>Yes</option>
                        <option value="0" <?php echo ($consignment['notify_customers'] != 1 ? 'selected' : '') ?>>No</option>
                    </select></td>
            </tr>
            <tr>
                <td><?php echo (__('Delivery Instructions')) ?></td>
                <td><textarea  placeholder="Please enter delivery instructions if any..." id="delivery_instructions" name="delivery_instructions" rows="5" cols="80" ><?php echo ($consignment['delivery_instructions']); ?></textarea></td>
            </tr>
        </table>

    </div>
    <div class="clear"></div>
    <button onclick="return submitForm()" class="scalable save submit-button" type="button" title="Submit"><span><span><span>Update Consignment</span></span></span></button>

</form>
<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui',
        'Magento_Ui/js/modal/modal',
        'prototype'
                // 'Magento_Sales/order/view/post-wrapper',
                // 'Magento_Sales/order/create/giftmessage'

    ], function ($) {
        $jEparcel = jQuery.noConflict();
    });
</script>
<script type="text/javascript">
<?php if ($use_order_total_weight == 1): ?>
        var weight = '<?php echo $weight ?>';
        var weightPerArticle = '<?php echo $weightPerArticle ?>';
<?php endif; ?>
    function submitForm()
    {
        var valid = true;
        $jEparcel('.required-entry').each(function () {
            var value = $jEparcel.trim($jEparcel(this).val());
            if (value.length == 0 && valid)
            {
                valid = false;
            }
        });
        if (!valid)
        {
            alert('Please enter all the mandatory fields');
            return false;
        }
        $jEparcel('.positive-number').each(function () {
            var value = $jEparcel.trim($jEparcel(this).val());
            var label = $jEparcel(this).attr('label');
            if (isNaN(value))
            {
                alert(label + ' should be a number');
                valid = false;
            }

            value = parseInt(value);
            if (value < 0)
            {
                alert(label + ' should be a postive number');
                valid = false;
            }

        });
        if (!valid)
        {
            return false;
        }

<?php if ($use_order_total_weight == 1): ?>
            $jEparcel('.maximum-value').each(function () {
                var value = $jEparcel.trim($jEparcel(this).val());
                var label = $jEparcel(this).attr('label');
                value = parseFloat(value);
                if (value > weightPerArticle)
                {
                    alert('Allowed weight per article is ' + weightPerArticle);
                    valid = false;
                }

            });
            if (!valid)
            {
                return false;
            }

            var totalInputWeight = 0;
            $jEparcel('.article_weight').each(function () {
                var value = $jEparcel.trim($jEparcel(this).val());
                value = parseFloat(value);
                totalInputWeight += value;
            });

            if (totalInputWeight < weight)
            {
                if (!confirm('Combined article weight is less than the total order weight. Do you want to continue?')) {
                    return false;
                }
                $('edit_form').submit();
            } else
            {
                $('edit_form').submit();
            }
<?php else: ?>
            $('edit_form').submit();
<?php endif; ?>
    }
</script>
<script type="text/x-magento-init">
    {
    "#edit-form": {
    "validation": {}
    }
    }
</script>