<button
    type="button"
    class="scalable save"
    onclick="sendLog()">
    <span><?php echo $this->__('Send Log') ?></span>
</button>
<script>
    function sendLog() {
        $jEparcel("#ajaxloader").show();
        $jEparcel.ajax({
            type: "POST",
            url: '<?php echo $this->getUrl('ausposteParcel/index/sendlog'); ?>',
            success: function (data) {
                $jEparcel("#ajaxloader").hide();
                data = $jEparcel.trim(data);
                if (data.length > 0) {
                    alert(data);
                }
            }
        });
    }
</script>
<div id="ajaxloader" style="display:none;padding-top:10px;">
    <img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif'); ?>">
</div>