<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Reports Base for Magento 2
 */
/**
 * @var \Amasty\Reports\Block\Adminhtml\Report\Toolbar $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<h1 class="amreport-main-title">
    <?= $escaper->escapeHtml($block->getCurrentTitle()) ?>
</h1>
<?= /* @noEscape */ $block->getChildHtml('additional_info') ?>
