<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$this->ausposteparcelHelper = $objectManager->get('Biztech\Ausposteparcel\Helper\Data');
if ($this->ausposteparcelHelper->isEnabled()) {
    $order_id = $this->getRequest()->getParam('order_id');
    $info = $objectManager->get('Biztech\Ausposteparcel\Helper\Info');
    $code = $info->getOrderCarrier($order_id);
    if ($code == 'ausposteParcel') {
        $valid = $info->isOrderAddressValid($order_id);
        if ($valid != 1) {
            ?>
            <div class="address-validation" style="border:1px solid #FFA500; font-size:12px; 
                 font-weight:normal; color:#000; border-radius: 2px; margin:4px; padding: 4px; 
                 background-color:#FFFBF0; word-wrap:break-word">
                <p><?php echo $valid ?></p>
            </div>
            <?php
        }
    }
}
?>
<div class="entry-edit" id="sales_order_view"></div>
