<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\View */ ?>
<?php $order = $block->getOrder() ?>
<div>
    <?php
    if ($order->getIsVirtual()) : return '';
    endif;
    ?>

    <?php /* Shipping Method */ ?>
    <div class="admin__page-section-item order-shipping-method">
        <div class="admin__page-section-item-title">
            <span class="title"><?= /* @escapeNotVerified */ __('Shipping &amp; Handling Information') ?></span>
        </div>
        <div class="admin__page-section-item-content">
            <?php if ($order->getTracksCollection()->count()) : ?>
                <p><a href="#" id="linkId" onclick="popWin('<?= /* @escapeNotVerified */ $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($order) ?>', 'trackorder', 'width=800,height=600,resizable=yes,scrollbars=yes')" title="<?= /* @escapeNotVerified */ __('Track Order') ?>"><?= /* @escapeNotVerified */ __('Track Order') ?></a></p>
            <?php endif; ?>
            <?php if ($order->getShippingDescription()): ?>
                <strong><?= $block->escapeHtml($order->getShippingDescription()) ?></strong>

                <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                    <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
                <?php else: ?>
                    <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                <?php endif; ?>
                <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

                <?= /* @escapeNotVerified */ $_excl ?>
                <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                    (<?= /* @escapeNotVerified */ __('Incl. Tax') ?> <?= /* @escapeNotVerified */ $_incl ?>)
                <?php endif; ?>
                <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $infoHelper = $objectManager->get('Biztech\Ausposteparcel\Helper\Info');
                $code = $infoHelper->getOrderCarrier($this->getOrder()->getId());
                if ($code != 'ausposteParcel') {
                    if ($this->getOrder()->getState() != 'canceled' && $this->getOrder()->getState() != 'complete') {
                        ?>
                        <a onclick="changeShippingMethod('<?php echo $this->getOrder()->getId() ?>', this)" href="javascript:void(0)"><?= __("Change Shipping Method") ?></a>
                        <?php
                    }
                }
                ?>
            <?php else: ?>
                <?= /* @escapeNotVerified */ __('No shipping information available') ?>
            <?php endif; ?>
        </div>
        <div id="shipping-method-popup"></div>
    </div>
    <script type="text/javascript">
        function changeShippingMethod(orderId, target)
        {
            // var shipping_method_url = '<?php //echo $this->getUrl('biztech_ausposteparcel/consignmentshippingMethod');    ?>';
            var shipping_method_url = '<?php echo $this->getUrl('biztech_ausposteparcel/consignment/shipping'); ?>';

            new Ajax.Request(shipping_method_url, {
                method: 'post',
                parameters: {orderId: orderId},
                onSuccess: function (transport) {
                    var response = transport.responseText.evalJSON();
                    if (response.status == 'success') {
                        if ($('shipping-method-popup').innerHTML == '') {
                            $('shipping-method-popup').update(response.shipping_method);
                            window.shippingMethodPopup.setContent('shipping-method-popup', true, false);
                        } else {
                            $('shipping-method-popup').update(response.shipping_method);
                        }
                        window.shippingMethodPopup.showCenter(true, true);
                        setTimeout(function () {
                            var $shippingMethodPopupWrap = $('shipping-method-popup');
                            var wH = window.innerHeight;
                            $shippingMethodPopupWrap.setStyle({
                                width: 'auto'
                            });
                            $shippingMethodPopupWrap.setStyle({
                                'height': 0.1 * wH + 'px',
                                'overflow': 'auto',
                                'top': '100px'
                            });
                            window.shippingMethodPopup.setSize(window.shippingMethodPopup.width, $shippingMethodPopupWrap.getHeight(), true);
                        }.bind(this), 300);
                        if (target != undefined) {
                            window.shippingMethodPopup.target = target;
                        }
                    } else if (response.status == 'error') {
                        $('shipping-method-popup').update('');
                        alert(response.message);
                    }
                }
            });
        }

        window.shippingMethodPopup = new Window({
            className: 'magento',
            title: 'Choose Shipping Method',
            maximizable: false,
            minimizable: false,
            resizable: false,
            draggable: false,
            recenterAuto: false,
            top: '100',
            showEffectOptions: {duration: 0.1},
            hideEffectOptions: {duration: 0.1}
        });
        window.shippingMethodPopup.setZIndex(2000);
    </script>
    <script type="text/javascript">

        // $jEparcel3 = jQuery.noConflict();

        function submitForm3(orderId)
        {
            $jEparcel3 = jQuery.noConflict();
            var valid = true;
            var value = $jEparcel3.trim($jEparcel3('#ausposteParcel_shipping_option').val());
            if (value.length == 0 && valid)
            {
                valid = false;
                alert('Please select shipping option');
                return false;
            }

            if (valid)
            {
                var change_shipping_method_url = '<?php echo $this->getUrl('biztech_ausposteparcel/consignment/changeshipping'); ?>';
                new Ajax.Request(change_shipping_method_url, {
                    method: 'post',
                    parameters: {order_id: orderId, ausposteParcel_shipping_option: value},
                    onSuccess: function (transport) {
                        location.reload();
                    }
                });
            } else
            {
                return false;
            }
        }
    </script>
