<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Reports Base for Magento 2
 */
/** @var \Amasty\Reports\Block\Adminhtml\Navigation $block */
/** @var \Magento\Framework\Escaper $escaper */

$tooltipBlock = $block->getChildBlock('amreports.tooltip');
?>

<div class="amreports-menu-container" data-amreports-js="menu-container">
    <div class="amreports-head" data-amreports-js="menu">
        <h1 class="amreports-title"><?= $escaper->escapeHtml(__('Advanced Reports')) ?></h1>
        <div class="amreports-toogle"></div>
        <div class="amreports-close-container">
            <div class="amreports-close" data-amreports-js="close"></div>
        </div>
    </div>
    <div class="amreports-list" data-amreports-js="menu-list">
        <?php foreach ($block->getMenu() as $group): ?>
            <div class="amreports-item level-0<?php if (isset($group['active'])): ?> active<?php endif ?>"
                 data-amreports-js="accordion">
                <?php if (isset($group['url'])): ?>
                    <a class="amreports-label -dashboard"
                       href="<?= $escaper->escapeUrl($block->getUrl($group['url'])) ?>"
                       title="<?= $escaper->escapeHtml($group['title']) ?>">
                        <?= $escaper->escapeHtml($group['title']) ?>
                    </a>
                <?php else: ?>
                    <div class="amreports-label" data-amreports-js="heading">
                        <?= $escaper->escapeHtml($group['title']) ?>
                    </div>
                <?php endif ?>

                <div class="amreports-sublist" data-amreports-js="content">
                    <?php foreach ($group['children'] as $child): ?>
                        <?php $tooltipBlock->setConfig($child); ?>
                        <?php $isEnabled =!isset($child['isInstalled']) || $child['isInstalled']; ?>
                        <div class="amreports-item level-1<?= (isset($child['active'])) ? ' active' : '' ?>
                        <?= $escaper->escapeHtml($group['class'] ?? '') ?>">
                            <?php if (isset($child['url']) && $child['url'] && $isEnabled): ?>
                                <a href="<?= $escaper->escapeUrl($block->getUrl($child['url'])) ?>"
                                   class="amreports-link <?= $escaper->escapeHtml($child['class'] ?? '') ?>"
                                   title="<?= $escaper->escapeHtml($child['title']) ?>"
                                >
                                    <?php if (isset($child['isInstalled']) && $child['isInstalled']): ?>
                                        <i class="amreports-ico -am-installed"></i>
                                    <?php endif ?>
                                    <?= $escaper->escapeHtml($child['title']) ?>
                                </a>
                            <?php elseif (!$isEnabled): ?>
                                <div class="<?= $escaper->escapeHtml($child['class'] ?? '') ?>">
                                    <?= /* @noEscape */ $block->getChildHtml('amreports.tooltip', false) ?>
                                    <i class="amreports-ico -am-not-installed"></i>
                                    <?= $escaper->escapeHtml($child['title']) ?>
                                </div>
                            <?php else: ?>
                                <?= $escaper->escapeHtml($child['title']) ?>
                            <?php endif ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
         "amreports_menu": {}
    }
}
</script>
