<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Reports Base for Magento 2
 */ /** @var \Magento\Framework\Escaper $escaper */ ?>

<div class="amreports-menutoggle-block" data-amreports-js="menu-toggle-block">
    <button class="amreports-menutoggle-button"
            title="<?= $escaper->escapeHtmlAttr(__('Toggle menu')) ?>"
            data-amreports-js="menu-toggle"
            data-mage-init='{"amreports_menu_toggle":{}}'
    >
        <svg class="amreports-ico" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 28 19">
            <path fill-rule="evenodd"
                  d="M0 .855469h28V4.03876H0V.855469zM0 15.7108h28v3.1833H0v-3.1833zm0-7.42764h28v3.18324H0V8.28316z"
                  clip-rule="evenodd"
            />
        </svg>
    </button>
</div>
