<script type="text/javascript">

    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'mage/translate',
        'Magento_Checkout/js/model/full-screen-loader'
    ], function ($, alert, $t, fullScreenLoader) {
        $(document).ready(function () {

            $('input[name="city"]').live('change', function (event) {
                var regionText = $('select[name="region_id"] option:selected').text();
                var flag = getSelectedCheck();
                if (flag) {
                    alert({
                        content: $t(flag)
                    });
                    event.preventDefault();
                }
            });


            $('input[name="postcode"]').live('change', function (event) {
                var regionText = $('select[name="region_id"] option:selected').text();
                var flag = getSelectedCheck();
                if (flag) {
                    alert({
                        content: $t(flag)
                    });
                    event.preventDefault();
                }
            });



            $('select[name="region_id"]').live('change', function (event) {
                var regionText = $('select[name="region_id"] option:selected').text();
                var flag = getSelectedCheck();
                if (flag) {
                    alert({
                        content: $t(flag)
                    });
                    event.preventDefault();
                }
            });

        });


    });
    function getSelectedCheck()
    {
        var city = jQuery('input[name="city"]').val();
        var region_id = jQuery('select[name="region_id"]').val();
        var postcode = jQuery('input[name="postcode"]').val();

        if (city != '' && region_id != '' && postcode != '')
        {
            return true;
        } else {
            return false;
        }
    }
</script>