<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Reports Base for Magento 2
 */ /** @var \Amasty\Reports\Block\Adminhtml\Report\Chart $block */ ?>
<?php
$jsonData = $block->getDataArray();
$lineNumbers = $block->getLineNumbers();
?>

<div class="amreports-amchart-wrapper" data-role="amreports-content">
    <?php if ($lineNumbers): ?>

        <div id="chart-compare" class="amreports-amchart-container"></div>

        <script>
            require([
                "Amasty_Reports/vendor/amcharts4/core.min"
            ], function () {
                require([
                    "jquery",
                    "amreports_chart_compare"
                ], function ($) {
                    $('#chart-compare').compareCharts({
                        "data": <?= /* @noEscape */ $jsonData ?>,
                        "interval": "<?= /* @noEscape */ $block->getInterval(); ?>",
                        "currency": "<?= /* @noEscape */ $block->getCurrencySymbol('total'); ?>",
                    });
                });
            });
        </script>

        <div class="listing">
            <?= $block->getChildHtml() ?>
        </div>
    <?php endif; ?>
</div>
