<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Reports Base for Magento 2
 */
/* @var Escaper $escaper */
/* @var Chart $block */

use Amasty\Reports\Block\Adminhtml\Report\Chart;
use Magento\Framework\Escaper;

$axis = $block->getAxisFields();
$collection = $block->getCollection();
?>

<div class="amreports-amchart-wrapper" data-role="amreports-content">
    <?php if ($collection->getSize()): ?>

        <?php foreach ($collection as $item) {
            $chartData[] = [
                "title" => $escaper->escapeHtml($item->getData($axis['y'])),
                "value" => $escaper->escapeHtml($item->getData($axis['x']))
            ];
        } ?>

        <div id="chart-category" class="amreports-amchart-container" data-chart-identifier="title"></div>

        <script>
            require([
                "Amasty_Reports/vendor/amcharts4/core.min"
            ], function () {
                require([
                    "jquery",
                    "<?= /* @noEscape */ $block->getWidgetName('amreports_simple_pie_chart') ?>"
                ], function ($, widget) {
                    widget({
                        "data" : <?= /* @noEscape */ json_encode($chartData); ?>,
                        "currency" : "<?= /* @noEscape */ $block->getCurrencySymbol(); ?>",
                        "selectorInit" : "chart-category"
                    }, $('#chart-category'));
                });
            });
        </script>

        <div class="listing">
            <?= $block->getChildHtml() ?>
        </div>
    <?php endif; ?>
</div>
