<?php

/** @var MageMe\WebForms\Block\Form $block */

$_uid  = $block->getUid();
$_form = $block->getForm();
?>

<?php if($_form->getTitle()){ ?>
    <h1><?= $block->applyTranslation($_form->getTitle()); ?></h1>
<?php } ?>

<?php if ($block->isAjax()) { ?>
    <div id="webform_<?= $_uid ?>_success_text" class="std webforms-success-text"
         style="display: none"></div>
<?php } ?>

<?php
if ($block->getSuccess()) {
    ?>
    <div class="webforms-success-text">
        <?= $block->getSuccessText() ?>
    </div>
    <script>
        <?= $block->getAfterSubmissionScript(); ?>
    </script>
    <?php
}
if (!$block->getSuccess() || $_form->getIsDisplayedAfterSubmission()) {
    ?>

    <div id="webform_<?= $_uid ?>_form" class="webforms">

        <?php if ($block->getDescription()) { ?>
            <div class="webforms-description-text">
                <?= $block->getDescription(); ?>
            </div>
        <?php } ?>

        <?= $block->getFormBlock()->setTemplate('form/multistep/form.phtml')->toHtml() ?>

        <?php if ($_form->getBelowText()) { ?>
            <div id="<?= $_uid ?>form_below_text" class="webforms-below-text">
                <?= $block->applyTranslation($_form->getBelowText()); ?>
            </div>
        <?php } ?>

    </div>


    <?= $block->getScriptBlock()->toHtml() ?>

    <script>
        require(['MageMe_WebForms/js/multistep'], function (multistep) {
            multistep({
                uid: '<?= $_uid ?>',
                submitButtonText: '<?= $block->applyTranslation($_form->getSubmitButtonText()) ?>'
            });
        })
    </script>

    <?php
} // if(show_success)
